on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          declare db_pass=$(dd bs=24 count=1 if=/dev/urandom status=none | base64 | tr +/ _.)
          echo "pass = \"$db_pass\""
